// Generated by scripts/generate-bindings.py.
import { createActorWithInterface } from "../actor.js";
import { idlFactory } from "./ic_wasm_canister.did.js";
export { idlFactory } from "./ic_wasm_canister.did.js";
export const canisterId = process.env.CANISTER_ID_IC_WASM_CANISTER;
export const createActor = (canisterId, options = {}) =>
  createActorWithInterface(canisterId, idlFactory, options);
