#!/usr/bin/env python3
"""Generate both canister bindings and synchronize the runnable examples."""
from pathlib import Path
import shutil
import subprocess

ROOT = Path(__file__).resolve().parent.parent

def normalize(path):
    path.write_text("\n".join(line.rstrip() for line in path.read_text().splitlines()) + "\n")

for name in ("ic_cose_canister", "ic_wasm_canister"):
    normalize(ROOT / "src" / name / f"{name}.did")
subprocess.run(["dfx", "generate"], cwd=ROOT, check=True)
for name in ("ic_cose_canister", "ic_wasm_canister"):
    directory = ROOT / "src/declarations" / name
    # Keep network policy in the maintained factory; generated wrappers must
    # never replace the root key of a caller-supplied agent.
    (directory / "index.js").write_text(f'''// Generated by scripts/generate-bindings.py.
import {{ createActorWithInterface }} from "../actor.js";
import {{ idlFactory }} from "./{name}.did.js";
export {{ idlFactory }} from "./{name}.did.js";
export const canisterId = process.env.CANISTER_ID_{name.upper()};
export const createActor = (canisterId, options = {{}}) =>
  createActorWithInterface(canisterId, idlFactory, options);
''')
    (directory / "index.d.ts").write_text(f'''// Generated by scripts/generate-bindings.py.
import type {{ ActorSubclass, ActorConfig, Agent, HttpAgentOptions }} from "@icp-sdk/core/agent";
import type {{ Principal }} from "@icp-sdk/core/principal";
import type {{ IDL }} from "@icp-sdk/core/candid";
import type {{ _SERVICE }} from "./{name}.did";
export declare const idlFactory: IDL.InterfaceFactory;
export declare const canisterId: string | undefined;
export interface CreateActorOptions {{
  agent?: Agent;
  agentOptions?: HttpAgentOptions;
  actorOptions?: Partial<ActorConfig>;
}}
export declare const createActor: (
  canisterId: string | Principal, options?: CreateActorOptions
) => ActorSubclass<_SERVICE>;
''')
    example = ROOT / "examples/vetkeys/declarations" / name
    example.mkdir(parents=True, exist_ok=True)
    for filename in ("index.js", "index.d.ts", f"{name}.did", f"{name}.did.js", f"{name}.did.d.ts"):
        normalize(directory / filename)
        shutil.copyfile(directory / filename, example / filename)
shutil.copyfile(ROOT / "src/declarations/actor.js", ROOT / "examples/vetkeys/declarations/actor.js")
