// Generated by scripts/generate-bindings.py.
import type { ActorSubclass, ActorConfig, Agent, HttpAgentOptions } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import type { IDL } from "@icp-sdk/core/candid";
import type { _SERVICE } from "./ic_cose_canister.did";
export declare const idlFactory: IDL.InterfaceFactory;
export declare const canisterId: string | undefined;
export interface CreateActorOptions {
  agent?: Agent;
  agentOptions?: HttpAgentOptions;
  actorOptions?: Partial<ActorConfig>;
}
export declare const createActor: (
  canisterId: string | Principal, options?: CreateActorOptions
) => ActorSubclass<_SERVICE>;
