name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    # - uses: dfinity/setup-dfx@main
    - name: Build canisters
      run: |
        rustup target add wasm32-unknown-unknown
        cargo install ic-wasm
        mkdir out
        RUSTFLAGS="--cfg=getrandom_backend=\"custom\"" cargo build --target wasm32-unknown-unknown --release --locked -p ic_cose_canister -p ic_object_store_canister -p ic_wasm_canister
        for CAN in ic_cose_canister ic_object_store_canister ic_wasm_canister
        do
          cp "target/wasm32-unknown-unknown/release/$CAN.wasm" out/
          cp "src/$CAN/$CAN.did" "out/$CAN.did"
          WASM="out/$CAN.wasm"
          ic-wasm $WASM -o $WASM metadata candid:service -f "out/$CAN.did" -v public
          ic-wasm $WASM -o $WASM shrink
          ic-wasm $WASM -o $WASM optimize O3 --inline-functions-with-loops
          gzip $WASM
          SHA256="$(sha256sum < "out/$CAN.wasm.gz" | sed 's/ .*$//g')"
          echo $SHA256 > "out/$CAN.wasm.gz.$SHA256.txt"
        done
        ls -lah out
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: out/*
