name: Test
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dfinity/setup-dfx@main
      - name: Run tests
        run: |
          cargo fmt --all -- --check
          cargo clippy --verbose --workspace --all-targets --all-features -- -D warnings
          cargo test --verbose --workspace --all-features -- --nocapture
